# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
mullenglobal: # Replace with a single Patreon username
MullenglobalCanada: # Replace with a single Open Collective username
jasonmullenfreemason1@gmail.com: # Replace with a single Ko-fi username
npm/babel: # Replace with a single Tidelift platform-name/package-name e.g., npm/babe
@mullenglobal1: # Replace with a single Community Bridge project-name e.g., cloud-foundry
jasonmullen: # Replace with a single Liberapay username
Mullenglobal: # Replace with a single IssueHunt username
Mullenglobal: # Replace with a single Otechie usernam
Mullenglobal: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
